global using AuthifyPass.API.Core.DTOs;
global using AuthifyPass.API.Core.Guards;
global using AuthifyPass.API.Core.Interfaces;
global using AuthifyPass.API.Core.Interfaces.UseCases.RegisterClient;
global using AuthifyPass.API.UseCases.RegisterClient;
global using AuthifyPass.API.UseCases.Resources;
global using AuthifyPass.Entities.DTOs;
global using AuthifyPass.Entities.Interfaces;
global using Microsoft.Extensions.Localization;
