// <auto-generated />
using System;
using AuthifyPass.API.DataBaseContext.EF.DataContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuthifyPass.API.DataBaseContext.EF.Migrations
{
    [DbContext(typeof(WritableDbContext))]
    [Migration("20241127075722_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthifyPass.API.Repositories.Entities.ClientEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("CHAR(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("LastUpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Password")
                        .HasColumnType("CHAR(64)");

                    b.Property<string>("SharedSecret")
                        .IsRequired()
                        .HasColumnType("CHAR(64)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("AuthifyPass.API.Repositories.Entities.UserSecretEntity", b =>
                {
                    b.Property<string>("ClientId")
                        .HasColumnType("CHAR(32)");

                    b.Property<string>("UserId")
                        .HasColumnType("CHAR(64)");

                    b.Property<string>("ActiveSharedSecret")
                        .HasColumnType("CHAR(64)");

                    b.Property<DateTime>("CreatetAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastRotatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PreviousSecretExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PreviousSharedSecret")
                        .HasColumnType("CHAR(64)");

                    b.HasKey("ClientId", "UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AuthifyPass.API.Repositories.Entities.UserSecretEntity", b =>
                {
                    b.HasOne("AuthifyPass.API.Repositories.Entities.ClientEntity", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .HasPrincipalKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
