global using AuthifyPass.Client;
global using AuthifyPass.Client.HttpClients;
global using AuthifyPass.Client.Models;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using System.Globalization;
global using System.Net;
global using System.Net.Http.Json;
global using System.Text.Json;
